"""
cmux-skills :: agent-status :: Hermes hook handler  (generated by cmux-skills)

Maps Hermes agent lifecycle events to cmux tab states by shelling out to the
cmux-skills CLI. The CLI itself owns all the logic (blocked-marker precedence,
overlapping-run counting, color choices, no-op when outside cmux), so this
handler stays dumb and fast.

Do not edit by hand — re-run `cmux-skills install hermes` to regenerate.
"""

import os
import subprocess

# Invocation of the cmux-skills CLI, baked in at install time.
CLI = __CLI_COMMAND__

EVENT_TO_STATE = {
    "agent:start": "working",      # a run started -> green
    "agent:end": "done",           # idle/finished this turn -> yellow (unless blocked)
    "session:end": "normalize",    # /new or /reset -> drop stale state, KEEP a real block
    "gateway:startup": "normalize",  # recovery: drop stale non-blocked state
}


def _run(state):
    # Only meaningful inside a cmux pane; the CLI also guards this, but we skip
    # the spawn entirely when there's nothing to target.
    if not os.environ.get("CMUX_WORKSPACE_ID"):
        return
    try:
        subprocess.Popen(
            CLI + ["status", state],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except Exception:
        # Never let a status signal break the agent pipeline.
        pass


def handle(event_type, context=None):
    state = EVENT_TO_STATE.get(event_type)
    if state:
        _run(state)
